doku

diff --git a/concieggs/remote/rpeggc/client_connect b/concieggs/remote/rpeggc/client_connect
--- a/concieggs/remote/rpeggc/client_connect
+++ b/concieggs/remote/rpeggc/client_connect
@@ -6,6 +6,11 @@
 
 addr="$1"
 
+if [ ! "$addr" ]; then
+    echo "Missing address!"
+    exit 1
+fi
+
 rm -f commands outputs
 mkfifo commands outputs
 
