Træk alle DanNet-relationer ud i simple filer.  Luk #146.
Også hotburn2.

Følgende relationsgrupper har over 1000 relationer:

hyponymOf: 64712
domain: 41332
roleAgent: 34225
usedFor: 23190
partHolonymOf: 13745
madeBy: 11741
involvedAgent: 11007
usedForObject: 6938
partMeronymOf: 5872
eqSynonymOf: 4875
madeofHolonymOf: 4263
concerns: 3192
locationMeronymOf: 2939
xposNearSynonymOf: 2286
memberHolonymOf: 2074
instanceOf: 1309
memberMeronymOf: 1048

diff --git a/concieggs/db/DanNet-tools/find_relations b/concieggs/db/DanNet-tools/find_relations
--- a/concieggs/db/DanNet-tools/find_relations
+++ b/concieggs/db/DanNet-tools/find_relations
@@ -1,18 +1,30 @@
 #!/bin/sh
 #
-# Find hyponyms.  Also do some filtering to keep them nice.
+# Find word relations.  Also do some filtering to keep them nice.
 #
-# Run once.
+# Run once for each relation.  It's pretty slow (and stupid).
+#
+# Usage: ./find_relations RELATION
+#
+# Looks for instances of RELATION (e.g. 'hyponymOf'), and saves them
+# into the file ../DanNet/RELATION with each line of the format 'X<Y',
+# where X has the asked-for relation to Y.
 
 cd "$(dirname "$0")"
 db="../DanNet-2.2_csv"
+
+relation="$1"
+if ! [ "$relation" ]; then
+   echo "error: missing relation argument" > /dev/stderr
+   exit 1
+fi
 
 f() {
     grep -E "^$(grep -E "^[0-9]+@[0-9]+@$1@" "$db/wordsenses-utf-8.csv" | cut -d@ -f2)@" "$db/words-utf-8.csv" \
         | cut -d@ -f2
 }
 
-cat "$db/relations-utf-8.csv" | grep hyponymOf | while read line; do
+cat "$db/relations-utf-8.csv" | grep "$relation" | while read line; do
     x="$(echo $line | cut -d@ -f1)"
     y="$(echo $line | cut -d@ -f4)"
     f "$x" | while read xf; do
@@ -25,4 +37,4 @@ cat "$db/relations-utf-8.csv" | grep hyponymOf | while read line; do
             echo "$xf<$yf"
         done
     done
-done > hyponyms
+done > "../DanNet/$relation"
