woop

diff --git a/concieggs/eggspi/compile b/concieggs/eggspi/compile
--- a/concieggs/eggspi/compile
+++ b/concieggs/eggspi/compile
@@ -10,7 +10,7 @@ fi
 srcfile=$(find $CONCIEGGS_DIR/compiled -name "$(basename "$1").*")
 
 if ! [ "$srcfile" ]; then
-    echo "$0: cannot find source for program '$srcfile' does not exist" >&2
+    echo "$0: cannot find source for program '$(basename "$1")'" >&2
     exit 3
 fi
 
